CREATE DATABASE Prubea_MySQL;
USE Prubea_MySQL;
CREATE TABLE HOLI(
  Id INT NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(25) NOT NULL,
  PRIMARY KEY (Id)
);
INSERT INTO HOLI VALUES (1, "HOLA");
INSERT INTO HOLI VALUES (2, "ALBERT");
INSERT INTO HOLI VALUES (3, "JUAN");
