CREATE DATABASE Prueba_Postgres;
USE Prueba_Postgres;
CREATE TABLE HOLI(
  Id INT NOT NULL PRIMARY KEY,
  Apellido VARCHAR(25) NOT NULL
);
INSERT INTO HOLI VALUES (1, "MUNDO");
INSERT INTO HOLI VALUES (2, "CAMUS");
INSERT INTO HOLI VALUES (3, "LOPEZ");
